services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: todo_sql_server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ToDo!Pass123
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: WebAPI/Dockerfile 
    container_name: todo_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ToDoListDb;User Id=sa;Password=ToDo!Pass123;TrustServerCertificate=True;MultipleActiveResultSets=true
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  sqldata: